### Kultury starożytne i cywilizacje pozaeuropejskie 

* Pierre du Bourguet Sztuka Koptów

* Jadwiga Lipińska Sztuka egipska

* Frederick Dockstader Sztuka Ameryki 1, 2

* Brain Doe Południowa Arabia

* Rudolf Drossler Wenus epoki lodowcowej

* Douglas Fraser Sztuka prymitywna

* Peter S. Garlake Wielkie Zimbabwe

* Michał Gawlikowski Sztuka Syrii

* Bernhard Jacobi Tajemnice świątyń i pałaców

* E. Jastrzębowska Sztuka wczesnochrześcijańska

* A. Mierzejewski Sztuka starożytnego wschodu 1, 2

* Jolanta Młynarszyk Sztuka Cypru

* Austen Henry Layard W poszukiwaniu Niniwy

* J. V. Luce Homer i epoka heroiczna

* J. V. Luce Koniec Atlantydy

* G.-C. Picard Sztuka rzymska

* B. Rutkowski Sztuka egejska

* P. Shinne Meroe

* B. Stawiński Sztuka Azji Środkowej

* W. Tomkiewicz Rokoko

### Czarna seria

* Jean-Pierre Babelon Sztuka hiszpańska

* Andre Chastel Sztuka włoska

* Z. Świechowski Sztuka romańska

* J. P. Couchoud Sztuka franuska

* J. Pavel Sztuka Czechosłowacji

* V. Florea Sztuka rumuńska

* F. Vasconcelos Sztuka portugalska

* Polska sztuk przedromańska i romańska

* Polska sztuka gotycka

* Polska sztuka XVII wieku

* Polska sztuka XVIII wieku

* Polska sztuka walcząca 1939-1945

* Sztuka Polski Ludowej
